<<<<<<< HEAD
baseURL: https://example.com
=======
baseURL: https://www.tshdmtmr.com
>>>>>>> cf5c3bc (# Go go!!)
canonifyURLs: no
relativeURLs: no
theme: hugo-theme-relearn
languageCode: en
defaultContentLanguage: en
<<<<<<< HEAD
title: Hugo Relearn Documentation
=======
title: tshdmtmr
>>>>>>> cf5c3bc (# Go go!!)
params:
  author: Sören Weber
  description: Documentation for Hugo Relearn Theme
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: no
  disableSeoHiddenPages: yes
  editURL: https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content
  mermaidInitialize: '{ "securityLevel": "loose"}'
  showVisitedLinks: yes
  themeVariant:
    - relearn-light
    - relearn-dark
    - learn
    - neon
    - blue
    - green
    - red
  titleSeparator: '::'
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    guessSyntax: no
    noClasses: no
server:
  headers:
    - for: '**.html'
      values:
        X-UA-Compatible: IE=edge
Languages:
  en:
    landingPageName: <i class='fas fa-home'></i> Home
    landingPageURL: /
    languageName: English
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> GitHub repo
          url: https://github.com/McShelby/hugo-theme-relearn
          weight: 10
        - name: <i class='fas fa-fw fa-camera'></i> Showcases
          url: more/showcase/
          weight: 11
        - identifier: hugodoc
          name: <i class='fas fa-fw fa-bookmark'></i> Hugo Documentation
          url: https://gohugo.io/
          weight: 20
        - name: <i class='fas fa-fw fa-bullhorn'></i> Credits
          url: more/credits/
          weight: 30
        - name: <i class='fas fa-fw fa-tags'></i> Tags
          url: tags/
          weight: 40
    title: Documentation for Hugo Relearn Theme
    weight: 1
  pir:
    landingPageName: <i class='fas fa-home'></i> Arrr! Home
    landingPageURL: /pir/
    languageName: Arrr! Pirrrates
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> GitHub repo
          url: https://github.com/McShelby/hugo-theme-relearn
          weight: 10
        - name: <i class='fas fa-fw fa-camera'></i> Showcases
          url: more/showcase/
          weight: 11
        - identifier: hugodoc
          name: <i class='fas fa-fw fa-bookmark'></i> Cap'n Hugo Documentat'n
          url: https://gohugo.io/
          weight: 20
        - name: <i class='fas fa-fw fa-bullhorn'></i> Crrredits
          url: more/credits/
          weight: 30
        - name: <i class='fas fa-fw fa-tags'></i> Arrr! Tags
          url: tags/
          weight: 40
    title: Documentat'n fer Cap'n Hugo Relearrrn Theme
    weight: 1
