---
title: 'Under Construction'
author: "tshdmtmr"
date: '2022/02/20'
categories: ["R"]
tags: ["RMarkdown"]
---


## やりたい事と大まかな流れ
- RMarkdownを使って、簡単に静的Webサイトを更新していくこと。
- その為に、RStudio、GitHub、Netlifyを使う。
- Rライブラリのblogdownを使うと、所定のフォルダに.Rmdファイルを放り込むだけで、.htmlファイルが自動生成される。
	- .mdファイルでも良いらしいが、Rスクリプトを実行したい場合は、.Rmdで。
	- RStudio上で、blogdown:::serve_site()を実行しておく。
		- すると、エディタで保存するタイミングで、.htmlファイルが自動生成されます。
			- 凄すぎる
- blogdownが自動生成したファイルを、RStudioからGitを使って、GitHubのリモートレポジトリにcommit、pushする。
	- ここは手動
- 同時に、Netlify側で、deploy先をGitHubのリモートレポジトリに指定しておく。
	- すると勝手に！build up してくれる
		- 凄すぎる

## 流れ
### GitHubにアクセスして、リモートレポジトリを作っておく

### RStudioから、projectを作る
- File > New Project > Version Control > Git
- Repository URL: に先に発行しておいたリモートレポジトリのURLを貼り付ける
- ローカルのディレクトリを間違えない様に注意して・・、プロジェクト作成

### RStudioから、blogdown:::new_siteを実行する
- Hugoのthemeを選んでおく。
	- Hugoというのは、静的サイトジェネレーター
	- Jekyllも使えるらしい
- 下記を実行
	- blogdown::new_site(theme = 'McShelby/hugo-theme-relearn')
	- 後からHugoのテーマは変えられるらしいが、まだ、やってない
- content/post 以下のファイルが公開される

### RStudioから、blogdown:::serve_site()を実行する
- RStudioのAddinsから、“Serve Site”をクリックしても良し
- RStudioのtoolbarにある、'Knit button' を押さない様に注意！

### Netlifyに接続
- 下記にアクセス
	- https://www.netlify.com
- 初回は、独自ドメインやら、何やら設定する
- deploy先は、Gitのリモートレポジトリを指定
- GitHubにpushした後に、Netlifyからdeployを実行すると、サイトが更新される

# ファイルの置き場所
- '/Users/tm/Dropbox/rstudio/public/post/'

## 新規ファイルのcommit 〜 push 〜 publish
-  GitのコマンドはRStudioから全て実行できる
- まず、RStudioから、rstudio.Rprojを開く 
- status
	- RStudioのGitコンソールに表示されている
- commit
- push


## Hugo
- これから研究

## Misc
- Gitにeditorの登録をしておくと便利らしい

